[package]
name = "examples3d"
version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true

[features]
default = ["webgpu", "rayon"] # enable rayon since 3D has several more cells to deal with.
unsafe_remove_boundchecks = ["taser-em3d/unsafe_remove_boundchecks"]
rayon = ["taser-em3d/rayon", "taser-em-testbed3d/rayon"]
webgpu = ["taser-em3d/webgpu"]
metal = ["taser-em3d/metal"]
cpu = ["taser-em3d/cpu"]
cpu-parallel = ["cpu", "taser-em3d/cpu-parallel"]
cuda = ["taser-em3d/cuda"]

[dependencies]
taser-em-testbed3d.workspace = true
kiss3d.workspace = true

[dependencies.taser-em3d]
path = "../crates/taser-em3d"
default-features = false

[[bin]]
name = "examples3d"
path = "main.rs"