[workspace]
members = [
    "crates/taser-em1d",
    "crates/taser-em-shaders1d",
    "crates/taser-em-testbed1d",
    "examples1d",
    "crates/taser-em2d",
    "crates/taser-em-shaders2d",
    "crates/taser-em-testbed2d",
    "examples2d",
    "crates/taser-em3d",
    "crates/taser-em-shaders3d",
    "crates/taser-em-testbed3d",
    "examples3d",
    "crates/taser-em-bench",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Nilson Sampath Jayasinghe Vidana Patiranage <nilsonjvidana@gmail.com>"]
repository = "https://github.com/nsjvidana/taser-em/"
categories = [
    "science",
    "simulation",
    "mathematics",
]
keywords = ["physics", "electromagnetics", "fdtd", "n-dimensional"]
license = "Apache-2.0"
edition = "2024"

[workspace.dependencies]
parry3d = "0.28"
khal = { version = "0.2.1", features = ["derive"] }
khal-builder = "0.2.1"
khal-std = "0.2.1"
spirv-std = { version = "0.10.0-alpha.1", features = ["default"] }
kiss3d = "0.44.0"
glamx = { version = "0.3", features = ["bytemuck"] }
mesh-loader = { version = "0.1.13", features = ["stl", "collada", "obj"] }
bytemuck = "1"
itertools = "0.15"
include_dir = "0.7"
thiserror = { version = "2", default-features = false, features = ["std"] }
derivative = "2"
anyhow = "1"
pollster = { version = "0.4", features = ["macro"] }

# Internal crates
taser-em1d = { version = "0.1.0", path = "crates/taser-em1d" }
taser-em-shaders1d = { version = "0.1.0", path = "crates/taser-em-shaders1d" }
taser-em-testbed1d = { version = "0.1.0", path = "crates/taser-em-testbed1d" }
taser-em2d = { version = "0.1.0", path = "crates/taser-em2d" }
taser-em-shaders2d = { version = "0.1.0", path = "crates/taser-em-shaders2d" }
taser-em-testbed2d = { version = "0.1.0", path = "crates/taser-em-testbed2d" }
taser-em3d = { version = "0.1.0", path = "crates/taser-em3d" }
taser-em-shaders3d = { version = "0.1.0", path = "crates/taser-em-shaders3d" }
taser-em-testbed3d = { version = "0.1.0", path = "crates/taser-em-testbed3d" }
rayon = "1.1"

# Compile build dependencies to speed up shader compilation times
[profile.release.build-override]
opt-level = 3
codegen-units = 16
[profile.dev.build-override]
opt-level = 3
