[workspace]
members = [
    "crates/taser-em1d",
    "crates/shaders/taser-em-shaders1d",
    "crates/taser-em2d",
    "crates/shaders/taser-em-shaders2d",
    "crates/taser-em3d",
    "crates/shaders/taser-em-shaders3d",
    "crates/taser-em-testbed",
    "crates/taser-em-build",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Nilson Sampath J Vidanapatiranage <nilsonjvidana@gmail.com>"]
# TODO: repository = ""
categories = [
    "science",
    "simulation",
    "mathematics",
]
keywords = ["physics", "electromagnetics", "fdtd", "n-dimensional"]
# TODO: license = ""
# TODO: rust-version = ""
edition = "2024"

[workspace.dependencies]
parry3d = "0.28"
khal = { version = "0.2.0", features = ["derive"] }
khal-builder = "0.2.0"
khal-std = "0.2.0"
glamx = { version = "0.3", features = ["bytemuck"] }
bytemuck = "1"
include_dir = "0.7"
derivative = "2"

# Compile build dependencies to speed up shader compilation times
[profile.release.build-override]
opt-level = 3
codegen-units = 16
[profile.dev.build-override]
opt-level = 3
