[package]
name = "taser-em-macros"
version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true

[lib]
name = "taser_em_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "2.0.77"
quote = "1.0.37"
proc-macro2 = "1.0.86"