[package]
name = "taser-em3d"
version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true

[lints]
rust.unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("dim1", "dim2"))',
    'cfg(target_arch, values("spirv"))',
] }

[features]
default = ["dim3", "webgpu"]
dim3 = []
render = []
unsafe_remove_boundchecks = ["taser-em-shaders/unsafe_remove_boundchecks"]
rayon = ["dep:rayon"]
webgpu = ["khal/webgpu"]
metal = ["khal/metal"]
cpu = ["taser-em-shaders/cpu", "khal/cpu"]
cpu-parallel = ["cpu", "taser-em-shaders/cpu-parallel"]
cuda = ["khal/cuda", "khal-builder/cuda", "taser-em-shaders/cuda"]

[lib]
name = "taser_em3d"
path = "../../src/lib.rs"
required-features = ["dim3"]

[dependencies]
parry3d.workspace = true
khal.workspace = true
taser-em-shaders = { package = "taser-em-shaders3d", path = "../taser-em-shaders3d" }
glamx.workspace = true
rayon = { workspace = true, optional = true }
itertools.workspace = true
include_dir.workspace = true
derivative.workspace = true

[build-dependencies]
khal-builder.workspace = true
taser-em-shaders = { package = "taser-em-shaders3d", path = "../taser-em-shaders3d" }