[package]
name = "taser-em-testbed2d"
version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true

[lints]
rust.unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("dim1", "dim3"))',
    'cfg(target_arch, values("spirv"))',
] }

[features]
default = ["dim2"]
dim2 = []
rayon = ["dep:rayon"] # rayon breaks the visualizer for some reason...

[lib]
name = "taser_em_testbed2d"
path = "../../src_testbed/src/lib.rs"
required-features = ["dim2"]

[dependencies]
kiss3d.workspace = true
khal.workspace = true
rayon = { workspace = true, optional = true }
glamx.workspace = true
anyhow.workspace = true

[dependencies.taser_em]
package = "taser-em2d"
path = "../taser-em2d"
version = "0.1.0"
features = ["render"]