[package]
name = "taser-em1d"
version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true

[lints]
rust.unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("dim2", "dim3"))',
    'cfg(target_arch, values("spirv"))',
] }

[features]
default = ["dim1", "webgpu"]
dim1 = []
render = []
rayon = ["dep:rayon"]
webgpu = ["khal/webgpu"]
cpu = ["khal/cpu", "taser-em-shaders/cpu"]
cpu-parallel = ["cpu", "taser-em-shaders/cpu-parallel"]
cuda = ["khal/cuda", "khal-builder/cuda", "taser-em-shaders/cuda"]

[lib]
name = "taser_em1d"
path = "../../src/lib.rs"
required-features = ["dim1"]

[dependencies]
parry3d.workspace = true
khal.workspace = true
taser-em-shaders = { package = "taser-em-shaders1d", path = "../taser-em-shaders1d" }
glamx.workspace = true
rayon = { workspace = true, optional = true }
itertools.workspace = true
include_dir.workspace = true
derivative.workspace = true

[build-dependencies]
khal-builder.workspace = true
taser-em-build.workspace = true
taser-em-shaders = { package = "taser-em-shaders1d", path = "../taser-em-shaders1d" }