[package]
name = "taser-em-testbed"
version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true

[dependencies]
taser-em1d = { path = "../taser-em1d", features = ["render"] }
kiss3d = "0.44.0"
khal.workspace = true
glamx.workspace = true