[package]
name = "examples2d"
version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true

[features]
default = ["webgpu"]
unsafe_remove_boundchecks = ["taser-em2d/unsafe_remove_boundchecks"]
#rayon = ["taser-em2d/rayon", "taser-em-testbed2d/rayon"]
rayon = ["taser-em2d/rayon"] # Testbed rayon is broken at the moment
webgpu = ["taser-em2d/webgpu"]
metal = ["taser-em2d/metal"]
cpu = ["taser-em2d/cpu"]
cpu-parallel = ["cpu", "taser-em2d/cpu-parallel"]
cuda = ["taser-em2d/cuda"]

[dependencies]
taser-em-testbed2d.workspace = true
kiss3d.workspace = true

[dependencies.taser-em2d]
path = "../crates/taser-em2d"

[[bin]]
name = "examples2d"
path = "main.rs"