[package]
name = "taser-em-shaders1d"
version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true
links = "taser-em-shaders1d"
build = "../build.rs"

[lints]
rust.unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("dim2", "dim3"))',
    'cfg(target_arch, values("spirv"))',
] }

[features]
default = ["dim1"]
dim1 = []
cpu = ["khal-std/cpu"]
cpu-parallel = ["khal-std/cpu-parallel"]
cuda = ["khal-std/cuda"]

[lib]
name = "taser_em_shaders1d"
path = "../src/lib.rs"
required-features = ["dim1"]

[dependencies]
khal-std.workspace = true
bytemuck.workspace = true

[target.'cfg(not(any(target_arch = "spirv", target_arch = "nvptx64")))'.dependencies]
khal.workspace = true

[build-dependencies]
khal-std.workspace = true
taser-em-build.workspace = true